<?php

namespace App\Event;

use Symfony\Component\HttpFoundation\Request;
use App\Entity\User;
class EventQueue
{
    const EVENT_LOGIN = "LOGIN";
    const EVENT_ADMIN_USER_ADD = "ADMIN_USER_ADD";
    const EVENT_ADMIN_USER_DELETE = "ADMIN_USER_DELETE";
    const EVENT_ADMIN_USER_UPDATE = "ADMIN_USER_UPDATE";
    const EVENT_ADMIN_CUSTOM_DOMAIN_ENABLE = "ADMIN_CUSTOM_DOMAIN_ENABLE";
    const EVENT_ADMIN_CUSTOM_DOMAIN_DISABLE = "ADMIN_CUSTOM_DOMAIN_DISABLE";
    const EVENT_FIREWALL_RULE_CREATE = "FIREWALL_RULE_CREATE";
    const EVENT_FIREWALL_RULE_DELETE = "FIREWALL_RULE_DELETE";
    const EVENT_FIREWALL_RULE_UPDATE = "FIREWALL_RULE_UPDATE";
    const EVENT_SERVICE_RESTART = "SERVICE_RESTART";
    const EVENT_PROFTPD_MASQUERADE_ADDRESS_UPDATE = "MASQUERADE_ADDRESS_UPDATE";
    const EVENT_INSTANCE_TIMEZONE_UPDATE = "INSTANCE_TIMEZONE_UPDATE";
    const EVENT_INSTANCE_REBOOT = "INSTANCE_REBOOT";
    const EVENT_DATABASE_SERVER_ADD = "DATABASE_SERVER_ADD";
    const EVENT_DATABASE_SERVER_EDIT = "DATABASE_SERVER_EDIT";
    const EVENT_DATABASE_SERVER_DELETE = "DATABASE_SERVER_DELETE";
    const EVENT_DATABASE_SERVER_CHANGE = "DATABASE_SERVER_CHANGE";
    const EVENT_AWS_ACCESS_KEYS_UPDATE = "AWS_ACCESS_KEYS_UPDATE";
    const EVENT_AWS_IMAGES_SETTINGS_UPDATE = "AWS_IMAGES_SETTINGS_UPDATE";
    const EVENT_AWS_IMAGE_CREATE = "AWS_IMAGE_CREATE";
    const EVENT_AWS_IMAGE_DELETE = "AWS_IMAGE_DELETE";
    const EVENT_DO_ACCESS_TOKEN_UPDATE = "DO_ACCESS_TOKEN_UPDATE";
    const EVENT_DO_SNAPSHOTS_SETTINGS_UPDATE = "DO_SNAPSHOTS_SETTINGS_UPDATE";
    const EVENT_DO_SNAPSHOT_CREATE = "DO_SNAPSHOT_CREATE";
    const EVENT_DO_SNAPSHOT_DELETE = "DO_SNAPSHOT_DELETE";
    const EVENT_GCE_SERVICE_ACCOUNTS_UPDATE = "GCE_SERVICE_ACCOUNTS_UPDATE";
    const EVENT_GCE_SNAPSHOTS_SETTINGS_UPDATE = "GCE_SNAPSHOTS_SETTINGS_UPDATE";
    const EVENT_GCE_SNAPSHOT_CREATE = "GCE_SNAPSHOT_CREATE";
    const EVENT_GCE_SNAPSHOT_DELETE = "GCE_SNAPSHOT_DELETE";
    const EVENT_VULTR_API_KEY_UPDATE = "VULTR_API_KEY_UPDATE";
    const EVENT_VULTR_SNAPSHOTS_SETTINGS_UPDATE = "VULTR_SNAPSHOTS_SETTINGS_UPDATE";
    const EVENT_VULTR_SNAPSHOT_CREATE = "VULTR_SNAPSHOT_CREATE";
    const EVENT_VULTR_SNAPSHOT_DELETE = "VULTR_SNAPSHOT_DELETE";
    const EVENT_HETZNER_API_TOKEN_UPDATE = "HETZNER_API_TOKEN_UPDATE";
    const EVENT_HETZNER_SNAPSHOTS_SETTINGS_UPDATE = "HETZNER_SNAPSHOTS_SETTINGS_UPDATE";
    const EVENT_HETZNER_SNAPSHOT_CREATE = "HETZNER_SNAPSHOT_CREATE";
    const EVENT_HETZNER_SNAPSHOT_DELETE = "HETZNER_SNAPSHOT_DELETE";
    const EVENT_SITE_WORDPRESS_CREATE = "SITE_WORDPRESS_CREATE";
    const EVENT_SITE_NODEJS_CREATE = "SITE_NODEJS_CREATE";
    const EVENT_SITE_STATIC_CREATE = "SITE_STATIC_CREATE";
    const EVENT_SITE_PHP_CREATE = "SITE_PHP_CREATE";
    const EVENT_SITE_PYTHON_CREATE = "SITE_PYTHON_CREATE";
    const EVENT_SITE_REVERSE_PROXY_CREATE = "SITE_REVERSE_PROXY_CREATE";
    const EVENT_SITE_ROOT_DIRECTORY_UPDATE = "SITE_ROOT_DIRECTORY_UPDATE";
    const EVENT_SITE_NODEJS_SETTINGS_UPDATE = "SITE_NODEJS_SETTINGS_UPDATE";
    const EVENT_SITE_PHP_SETTINGS_UPDATE = "SITE_PHP_SETTINGS_UPDATE";
    const EVENT_SITE_PYTHON_SETTINGS_UPDATE = "SITE_PYTHON_SETTINGS_UPDATE";
    const EVENT_SITE_REVERSE_PROXY_SETTINGS_UPDATE = "SITE_REVERSE_PROXY_SETTINGS_UPDATE";
    const EVENT_SITE_USER_SETTINGS_UPDATE = "SITE_USER_SETTINGS_UPDATE";
    const EVENT_SITE_PAGE_SPEED_SETTINGS_UPDATE = "SITE_PAGE_SPEED_SETTINGS_UPDATE";
    const EVENT_SITE_PAGE_SPEED_CACHE_PURGE = "SITE_PAGE_SPEED_CACHE_PURGE";
    const EVENT_SITE_BLOCKED_COUNTRIES_UPDATE = 'site.blocked-countries.update';
    const EVENT_SITE_BLOCKED_IP_ADD = "SITE_BLOCKED_IP_ADD";
    const EVENT_SITE_BLOCKED_IP_DELETE = "SITE_BLOCKED_IP_DELETE";
    const EVENT_SITE_BASIC_AUTHENTIFICATION_SETTINGS = "SITE_BASIC_AUTHENTIFICATION_SETTINGS";
    const EVENT_SITE_CLOUDFLARE_SETTINGS = "EVENT_SITE_CLOUDFLARE_SETTINGS";
    const EVENT_SITE_BLOCKED_BOT_ADD = "SITE_BLOCKED_BOT_ADD";
    const EVENT_SITE_BLOCKED_BOT_DELETE = "SITE_BLOCKED_BOT_DELETE";
    const EVENT_SITE_DATABASE_ADD = "SITE_DATABASE_ADD";
    const EVENT_SITE_DATABASE_DELETE = "SITE_DATABASE_DELETE";
    const EVENT_SITE_DATABASE_USER_ADD = "SITE_DATABASE_USER_ADD";
    const EVENT_SITE_DATABASE_USER_EDIT = "SITE_DATABASE_USER_EDIT";
    const EVENT_SITE_DATABASE_USER_DELETE = "SITE_DATABASE_USER_DELETE";
    const EVENT_SITE_CERTIFICATE_INSTALL = "SITE_CERTIFICATE_INSTALL";
    const EVENT_SITE_CERTIFICATE_DELETE = "SITE_CERTIFICATE_DELETE";
    const EVENT_SITE_FTP_USER_ADD = "SITE_FTP_USER_ADD";
    const EVENT_SITE_FTP_USER_EDIT = "SITE_FTP_USER_EDIT";
    const EVENT_SITE_FTP_USER_DELETE = "SITE_FTP_USER_DELETE";
    const EVENT_SITE_SSH_USER_ADD = "SITE_SSH_USER_ADD";
    const EVENT_SITE_SSH_USER_EDIT = "SITE_SSH_USER_EDIT";
    const EVENT_SITE_SSH_USER_DELETE = "SITE_SSH_USER_DELETE";
    const EVENT_SITE_CRON_JOB_ADD = "SITE_CRON_JOB_ADD";
    const EVENT_SITE_CRON_JOB_EDIT = "SITE_CRON_JOB_EDIT";
    const EVENT_SITE_CRON_JOB_DELETE = "SITE_CRON_JOB_DELETE";
    const EVENT_SITE_VHOST_UPDATE = "EVENT_SITE_VHOST_UPDATE";
    const EVENT_SITE_DELETE = "SITE_DELETE";
    const EVENT_REMOTE_BACKUP_CREATE = "REMOTE_BACKUP_CREATE";
    const EVENT_REMOTE_BACKUP_EDIT = "REMOTE_BACKUP_EDIT";
    const EVENT_REMOTE_BACKUP_DELETE = "REMOTE_BACKUP_DELETE";
    const EVENT_SITE_VARNISH_CACHE_SETTINGS_UPDATE = "SITE_VARNISH_CACHE_SETTINGS_UPDATE";
    const EVENT_SITE_VARNISH_CACHE_PURGE = "SITE_VARNISH_CACHE_PURGE";
    private static array $queuedEvents = [];
    private static array $events = [];
    public static function addEvent($eventName, User $user, array $eventData = [], Request $request = null) : void
    {
        $events = self::getEvents();
        if (false !== array_search($eventName, self::$events)) {
            self::$queuedEvents[] = ["eventName" => $eventName, "eventData" => $eventData, "eventTime" => new \DateTime("now"), "user" => $user, "request" => $request];
        }
    }
    private static function getEvents() : array
    {
        if (true === empty(self::$events)) {
            $reflectionClass = new \ReflectionClass(__CLASS__);
            self::$events = $reflectionClass->getConstants();
        }
        return self::$events;
    }
    public static function getQueuedEvents() : array
    {
        return self::$queuedEvents;
    }
}