server {
  server_name _;
  listen 8443 ssl http2;
  listen [::]:8443 ssl http2;
  ssl_certificate_key /home/clp/services/nginx/ssl-certificates/private.key;
  ssl_certificate /home/clp/services/nginx/ssl-certificates/cert.crt;
  client_max_body_size 5048M;
  root /home/clp/htdocs/app/files/public;

  #access_log /home/clp/logs/nginx/access.log;
  error_log /home/clp/logs/nginx/error.log;

  location ~ /.well-known {
    auth_basic off;
    allow all;
  }

  set $basicAuth "off";

  if (-f /home/clp/services/nginx/basic-auth/credentials) {
    set $basicAuth "on";
  }

  if ($request_uri ~ ^/phpmyadmin) {
    set $basicAuth "off";
  }

  auth_basic $basicAuth;
  auth_basic_user_file /home/clp/services/nginx/basic-auth/credentials;

  rewrite ^/phpmyadmin$ /phpmyadmin/$1 permanent;

  location /file-manager/ {
    try_files $uri $uri/ /file-manager/index.php?$args;
    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_intercept_errors on;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      try_files $uri =404;
      fastcgi_pass unix:/run/clp-fm-php-fpm.sock;
      fastcgi_read_timeout 3600;
      fastcgi_send_timeout 3600;
      fastcgi_param HTTPS $fastcgi_https;
      fastcgi_param PHP_VALUE "
        error_log=/home/clp/logs/php/error.log;
        memory_limit=1024M;
        post_max_size=3G;
        upload_max_filesize=3G;
        max_execution_time=3600;";
    }
  }

  location /file-manager/backend/ {
    try_files $uri $uri/ /file-manager/backend.php?$args;
    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_intercept_errors on;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      try_files $uri =404;
      fastcgi_pass unix:/run/clp-fm-php-fpm.sock;
      fastcgi_read_timeout 3600;
      fastcgi_send_timeout 3600;
      fastcgi_param HTTPS $fastcgi_https;
      fastcgi_param PHP_VALUE "
        error_log=/home/clp/logs/php/error.log;
        memory_limit=1024M;
        post_max_size=3G;
        upload_max_filesize=3G;
        max_execution_time=3600;";
    }
  }

  try_files $uri $uri/ /index.php?$args;
  index index.php index.html index.htm;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri =404;
    fastcgi_pass unix:/run/clp-php-fpm.sock;
    fastcgi_read_timeout 3600;
    fastcgi_send_timeout 3600;
    fastcgi_param HTTPS $fastcgi_https;
    fastcgi_param PHP_VALUE "
      error_log=/home/clp/logs/php/error.log;
      memory_limit=1024M;
      max_execution_time=90;";
  }

  location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|eot|mp4|ogg|ogv|webm|swf)$ {
    add_header Access-Control-Allow-Origin "*";
    expires 30d;
    access_log off;
  }

  if (-f $request_filename) {
    break;
  }
}
